### ISSUE TITLE
Compiler conflicts in C++ code for gdistsamp

### ISSUE THREAD

**Issue by kenkellner** [rbchan/unmarked#134]
Opening this mainly to record some notes...there may be no need to change anything.

There are header file conflicts between `RcppArmadillo.h` and `R_ext/Applic.h` which I currently use to access `Rdqags` for numerical integration in the C++ code for `gdistsamp`. The only information I could find about dealing with this is, ironically, a [7-year old mailing list post](http://lists.r-forge.r-project.org/pipermail/rcpp-devel/2012-March/003557.html) by @rbchan where it looks like he ran into the same issue.

Despite the conflicts and resulting warnings the code compiles for me on Linux. I am not sure if Windows/Mac might have issues or if CRAN will complain on submission. 

If there are problems one alternative is to switch to using the [RcppNumerical](https://github.com/yixuan/RcppNumerical) package to handle integration instead of `Rdqags`. This would add dependencies to `RcppNumerical` and also `RcppEigen`.

I was able implement this change successfully in [this branch](https://github.com/kenkellner/unmarked/tree/use_RcppNumerical) for both `distsamp` and `gdistsamp`.

**Comment by rbchan** [comment]
Hi Ken,

I agree that we should deal with the header conflicts, and we should
probably stop using Rdqags. I just wonder if RcppNumerical is overkill for
this problem? Could we use a simple Reimann sum instead? Also, there are
analytical solutions to some of these integrals. Some of the analytical
solutions are implemented already, but not consistently among functions.

Richard

**Comment by kenkellner** [comment]
Resolved in #135
