### ISSUE TITLE
Can't make fitList from occuFP models

### ISSUE THREAD

**Issue by kenkellner** [rbchan/unmarked#147]
Probably need to convert fitList() into a method instead of a regular function.

**Comment by rbchan** [comment]
Good idea

**Comment by rbchan** [comment]
Andy, did you get around to submitting Ken's changes to CRAN? If you're too
busy, do you want me to do it?

**Comment by rbchan** [comment]
Hey man ,
Sorry about that ... if you have time that would be great ... on my way
home rider now and traveling again the next 2 weeks I’m afraid ... just no
time lately. Sorry man!

Great seeing you this week , wish I could have spent the whole week , what
a great meeting!
Regards
Andy

Sent from my iPhone

On Oct 3, 2019, at 12:35 PM, Richard Chandler <richard.chandlers@gmail.com>
wrote:

Andy, did you get around to submitting Ken's changes to CRAN? If you're too
busy, do you want me to do it?

**Comment by kenkellner** [comment]
I am working on a patch that's almost done for automated model selection with all covariate subsets (like `MuMIn::dredge()`) inspired by Dana Morin's talk. If you want to wait for that and the adjustments to `fitList` I will probably get them done in the next week.

**Comment by rbchan** [comment]
Ken, I'm a bit concerned that "all subsets" approaches can increase the
chance of finding spurious results. Is there a strong need to add that
functionality if it already exists in other packages?

Sorry I didn't get a chance to meet you at the meeting yesterday. Next time!

**Comment by kenkellner** [comment]
Well, I don't think there's any existing approach that works with unmarked models (given the unique multi-formula structure). But I understand the concern about questionable results.

The dredge stuff is really just a wrapper on a function for fitting a bunch of specific models together / in parallel. That at least seems worth including to me since many people seem to be fitting large numbers of models based on different hypotheses etc. and there currently isn't a quick way to do that.

**Comment by rbchan** [comment]
Ok, sounds good. Will you send the tar ball to Andy and me when it's ready?
Andy will upload it to cran.

**Comment by jaroyle** [comment]
hi fellas,
 I've been sicker than a dog since returning from TWS and hope to have my
head back above water later this week. Sorry to be out of touch. If someone
can send me the tarball I will upload it so as to not have to change
maintainer. Sorry to drop the ball on this but I have a trip next week that
I have to focus all burners on right now...
regards
andy
