### ISSUE TITLE
Add 'coresToUse' argument to 'parboot'

### ISSUE THREAD

**Issue by mikemeredith** [rbchan/unmarked#149]
Running `parboot` with `parallel=TRUE` obviously makes sense, but that currently means running workers on all-but-one of the available cores. If there are other apps using multiple cores, that causes problems.

I often have multiple instances of R running on a 24-core box, generally with `jagsUI::jags` taking 3 cores each. Trying to run a script with `parboot` on 23 cores at the same time is messy and means the timings from `jags` are meaningless.

It should be straightforward to add `coresToUse` to the arguments list, with something like `if(missing(coresToUse)) coresToUse <- detectCores() - 1`.

Thanks, Mike

**Comment by rbchan** [comment]
Good idea. @adamdsmith any chance you might have time to add this? @

**Comment by adamdsmith** [comment]
I’ll try to knock it out this morning.

**Comment by rbchan** [comment]
Great, thanks. What do you think about calling the argument `nCores` or `n.cores` or something shorter than `coresToUse`?

**Comment by kenkellner** [comment]
This also should be added to crossVal. I can add that based on whatever Adam calls the argument.

**Comment by adamdsmith** [comment]
The parboot function already has an argument `nsim` so to avoid multiple case types within the same function call I'll go with `ncores` unless there's strong objection.

**Comment by rbchan** [comment]
Sounds good to me

**Comment by mikemeredith** [comment]
Great, thanks a lot! -- Mike

**Comment by jaroyle** [comment]
hi fellas,
 thanks a lot for this... I will recompile and upload a new unmarked next
week I hope.
 I got some hate mail from CRAN about some issue with the current version
which might get the package yanked if it doesn't get resolved... (something
that doesn't work with R 4.0).
 Will send this email around..
regards
andy

**Comment by kenkellner** [comment]
Regarding that error, see #151
