### ISSUE TITLE
Consider distinction between package authors and collaborators

### ISSUE THREAD

**Issue by kenkellner** [rbchan/unmarked#173]
See https://github.com/rbchan/unmarked/pull/172#issuecomment-605958256

Some R maintainers provided guidelines in this paper:

https://journal.r-project.org/archive/2012-1/RJournal_2012-1_Hornik~et~al.pdf

> "aut" (Author):  Full  authors  who  have  made  substantial   contributions  to  the package  and should show up in the package citation."

> "ctb" (Contributor):  Authors who have made smaller  contributions  (such  as  code  patches etc.)   but should not show up in the  package citation.

> "cre" (Creator):  Package maintainer.

**Comment by rbchan** [comment]
Those guidelines sound good to me. Here is what I suggest:

Author: Ian Fiske, Richard Chandler, David Miller, Andy Royle, Jeff Hostetler, Rebecca Hutchinson, Adam Smith, Ken Kellner 

Contributor: Marc Kery (and several others who have contributed code. I would have to go through the git log to find all their names)

**Comment by kenkellner** [comment]
Output of `git shortlog -sne`, excluding people you already mentioned:

```
     9  Mike Meredith <mmeredith@wcsmsia>
     7  aurielfournier <aurielfournier@gmail.com>
     4  Ariel Muldoon <ariel.muldoon@oregonstate.edu>
     1  Chris Baker <ccmbaker@fas.harvard.edu>
     1  Stefan Theussl <stefan.theussl@wu.ac.at>
```

**Comment by rbchan** [comment]
I wonder if some folks contributed to branches that weren't pulled into master? If you look at `Insights > Contributors` on github, Ariel Muldoon, Chris Baker, and Stefan Theussl don't appear.

**Comment by kenkellner** [comment]
That git command should only summarize commits from the master branch. I think Github's collaborator page only lists the 10 authors with the most code contributed. 

If I search across all branches:

`git shortlog -s -n --all --no-merges`

I get the same list with one additional unknown person:

```
     1  fukayak <fukayak99@gmail.com>
```

**Comment by rbchan** [comment]
Ah okay, let's trust git then, and not github's tool. And we can ignore folks that didn't contribute to master.
