### ISSUE TITLE
Use Github actions for continuous integration

### ISSUE THREAD

**Issue by kenkellner** [rbchan/unmarked#196]
I think we could pretty easily add CI with Github actions. I've tested it with other packages. It's nice because you can auto-test builds on all major OS (including Mac).

**Comment by rbchan** [comment]
That would be great. Thanks Ken.

**Comment by kenkellner** [comment]
I've added it. There might be a bunch of failing build emails until I figure out all the required software, sorry.

**Comment by kenkellner** [comment]
[Working now](https://github.com/rbchan/unmarked/actions). I had to disable vignette checks because of issues getting the required latex packages installed.
