### ISSUE TITLE
Small typo in documentation for formatDistData

### ISSUE THREAD

**Issue by meriops** [rbchan/unmarked#236]
I might be wrong, but this has actually given me a bit of a headache while trying to format some data! ;-)
I believe that according to the notation in the rest of the page, the size of `effortMatrix` in `formatDistData` should read `M x T` (ie sites by occasions) rather than `M x J` (sites by distance bins) ...

**Comment by kenkellner** [comment]
Thanks, fixed in [a2c9c02](https://github.com/rbchan/unmarked/commit/a2c9c02a3d219f2c9279f918d77b9f4b41861af3)
