### ISSUE TITLE
Refactor gmultmix likelihood function

### ISSUE THREAD

**Issue by kenkellner** [rbchan/unmarked#240]
When counts are high the result can sometimes be infinite. I wonder if re-writing the function to be more like the `gdistremoval` one would prevent this.

Specifically this line (and the calculation of A just before it) is the issue:

https://github.com/rbchan/unmarked/blob/5063b596ad880b1cba772090c1e48eb13a7c7bdd/R/gmultmix.R#L118

**Comment by kenkellner** [comment]
I implemented the change in [this branch](https://github.com/kenkellner/unmarked/tree/gmultmix_refactor). It did increase the maximum counts that could be handled, but not enough to actually solve the issue the user was having. I'm not sure if it's worth merging since this is something of an outlier problem.

**Comment by rbchan** [comment]
@kenkellner Did the change slow down the likelihood calculation substantially? If so, I suppose I wouldn't merge it.

**Comment by kenkellner** [comment]
It's about the same speed as before. We know the current code works for the vast majority of situations - I suppose there isn't much reason to risk new bugs by merging this.

**Comment by rbchan** [comment]
Ok merge on
