### ISSUE TITLE
Write all likelihoods in C++

### ISSUE THREAD

**Issue by rbchan** [rbchan/unmarked#61]
gmultmix and gdistsamp are especially slow

**Comment by kenkellner** [comment]
Status:
- [X] gmultmix
- [X] occuRN
- [X] multinomPois
- [ ] colext
- [ ] gdistsamp
- [ ] occuFP
- [ ] pcount.spHDS

**Comment by rbchan** [comment]
Good enough. Thanks @kenkellner
